<?php namespace App\Model;

/**
 * Eloquent class to describe the 60A_sintegra table
 *
 * automatically generated by ModelGenerator.php
 */
class 60ASintegra extends \Illuminate\Database\Eloquent\Model
{
    protected $table = '60A_sintegra';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('fiscal_date');
    }

    protected $fillable = array('store_key', 'type', 'sub_type', 'fiscal_date', 'ecf_serial', 'pos_id', 'amount');


}
