<?php namespace App\Model;

/**
 * Eloquent class to describe the 60D_sintegra table
 *
 * automatically generated by ModelGenerator.php
 */
class 60DSintegra extends \Illuminate\Database\Eloquent\Model
{
    protected $table = '60D_sintegra';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('fiscal_date');
    }

    protected $fillable = array('store_key', 'type', 'sub_type', 'fiscal_date', 'ecf_serial', 'plu_id', 'quantity',
        'amount', 'base_amount', 'pos_id', 'tax_amount');


}
