<?php namespace App\Model;

/**
 * Eloquent class to describe the 60I_sintegra table
 *
 * automatically generated by ModelGenerator.php
 */
class 60ISintegra extends \Illuminate\Database\Eloquent\Model
{
    protected $table = '60I_sintegra';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('fiscal_date');
    }

    protected $fillable = array('store_key', 'type', 'sub_type', 'fiscal_date', 'ecf_serial', 'doc_model',
        'ticket_number', 'sequence', 'plu_id', 'quantity', 'amount', 'base_amount', 'pos_id', 'tax_amount', 'ecf_number',
        'amount_liq', 'amount_bru', 'discount', 'Z_number');


}
