<?php namespace App\Model;

/**
 * Eloquent class to describe the access_control table
 *
 * automatically generated by ModelGenerator.php
 */
class AccessControl extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'access_control';

    public $primaryKey = 'access_control_key';

    public $timestamps = false;

    protected $fillable = array('entity_key', 'agent_key', 'access_type_key', 'high_limit_value', 'low_limit_value',
        'high_limit_percent', 'low_limit_percent', 'high_limit_quantity');


}
