<?php namespace App\Model;

/**
 * Eloquent class to describe the accountant table
 *
 * automatically generated by ModelGenerator.php
 */
class Accountant extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'accountant';

    public $primaryKey = 'accountant_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('name', 'cnpj_cpf', 'crc', 'cep', 'logradouro', 'numero', 'complemento', 'bairro',
        'telefone', 'fax', 'email', 'store_city_code');


}
