<?php namespace App\Model;

/**
 * Eloquent class to describe the accum_extra table
 *
 * automatically generated by ModelGenerator.php
 */
class AccumExtra extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'accum_extra';

    public $primaryKey = 'fiscal_date';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('quantity', 'quantity_canc', 'amount', 'amount_canc');


}
