<?php namespace App\Model;

/**
 * Eloquent class to describe the accum_item table
 *
 * automatically generated by ModelGenerator.php
 */
class AccumItem extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'accum_item';

    public $primaryKey = 'plu_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('desc_plu', 'quantity', 'quantity_canc', 'amount', 'amount_canc', 'cost', 'cost_canc',
        'margin', 'return_quantity', 'return_amount', 'department_key', 'maker_key', 'received_quantity', 'received_amount',
        'pis_cofins');


}
