<?php namespace App\Model;

/**
 * Eloquent class to describe the accum_maker table
 *
 * automatically generated by ModelGenerator.php
 */
class AccumMaker extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'accum_maker';

    public $primaryKey = 'hour';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('quantity', 'quantity_canc', 'amount', 'amount_canc', 'cost', 'cost_canc', 'margin',
        'return_quantity', 'return_amount');


}
