<?php namespace App\Model;

/**
 * Eloquent class to describe the accum_item_extra table
 *
 * automatically generated by ModelGenerator.php
 */
class AccumItemExtra extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'accum_item_extra';

    public $primaryKey = 'invoice_type';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('desc_plu', 'quantity', 'amount', 'cost', 'department_key', 'maker_key');


}
