<?php namespace App\Model;

/**
 * Eloquent class to describe the accum_extended_media table
 *
 * automatically generated by ModelGenerator.php
 */
class AccumExtendedMedia extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'accum_extended_media';

    public $primaryKey = 'fiscal_date';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('quantity', 'quantity_canc', 'amount', 'amount_canc', 'quantity_pickup',
        'amount_pickup', 'amount_loan', 'media_id');


}
