<?php namespace App\Model;

/**
 * Eloquent class to describe the accum_log table
 *
 * automatically generated by ModelGenerator.php
 */
class AccumLog extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'accum_log';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('log_date');
    }

    protected $fillable = array('store_key', 'log_date', 'pos_number', 'log_msg_code', 'log_msg_data');


}
