<?php namespace App\Model;

/**
 * Eloquent class to describe the acquirr_type table
 *
 * automatically generated by ModelGenerator.php
 */
class AcquirrType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'acquirr_type';

    public $primaryKey = 'acquirr_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('acquirr_name');


}
