<?php namespace App\Model;

/**
 * Eloquent class to describe the address_type table
 *
 * automatically generated by ModelGenerator.php
 */
class AddressType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'address_type';

    public $primaryKey = 'address_type_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('address_type_name', 'address_type_send');


}
