<?php namespace App\Model;

/**
 * Eloquent class to describe the adm_geral table
 *
 * automatically generated by ModelGenerator.php
 */
class AdmGeral extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'adm_geral';

    public $primaryKey = 'transaction';

    public $timestamps = false;

    public function getDates()
    {
        return array('data_prescricao', 'start_time');
    }

    protected $fillable = array('cnpj_loja', 'cod_solicitacao', 'num_adm', 'crm', 'cpf', 'ticket_number', 'uni_federal',
        'data_prescricao', 'cod_indicador', 'cod_indicador_estorno', 'status_emporium', 'start_time', 'pos_number', 'store_key',
        'nome', 'valor_total', 'valor_ms', 'valor_paciente', 'valor_estorno');


}
