<?php namespace App\Model;

/**
 * Eloquent class to describe the adm_send table
 *
 * automatically generated by ModelGenerator.php
 */
class AdmSend extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'adm_send';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_change_time');
    }

    protected $fillable = array('table_name', 'field', 'name', 'description', 'tag', 'flag_online', 'flag_send',
        'last_change_time', 'module');


}
