<?php namespace App\Model\Model;

/**
 * Eloquent class to describe the agent_group table
 *
 * automatically generated by ModelGenerator.php
 */
class AgentGroup extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'agent_group';

    public $primaryKey = 'agent_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
