<?php

namespace App\Model;

/**
 * Eloquent class to describe the agent table
 *
 * automatically generated by ModelGenerator.php
 */
class Agent extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'agent';

    public $primaryKey = 'agent_key';

    public $timestamps = false;

    protected $fillable = array('agent_type', 'id', 'name', 'remark', 'sub_type');


}
