<?php namespace App\Model;

/**
 * Eloquent class to describe the agent_store table
 *
 * automatically generated by ModelGenerator.php
 */
class AgentStore extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'agent_store';

    public $primaryKey = 'agent_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
