<?php namespace App\Model;

/**
 * Eloquent class to describe the answer_data table
 *
 * automatically generated by ModelGenerator.php
 */
class AnswerData extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'answer_data';

    public $primaryKey = 'sequence';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('data_id', 'data_label', 'data_value');


}
