<?php namespace App\Model;

/**
 * Eloquent class to describe the backup_control table
 *
 * automatically generated by ModelGenerator.php
 */
class BackupControl extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'backup_control';

    public $primaryKey = 'backup_key';

    public $timestamps = false;

    public function getDates()
    {
        return array('creation_time');
    }

    protected $fillable = array('backup_type', 'creation_time', 'comment', 'menu_item', 'entity', 'access_control');


}
