<?php namespace App\Model;

/**
 * Eloquent class to describe the banking_block_transfer table
 *
 * automatically generated by ModelGenerator.php
 */
class BankingBlockTransfer extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'banking_block_transfer';

    public $primaryKey = 'block_transfer_key';

    public $timestamps = false;

    public function getDates()
    {
        return array('reference_date', 'creation_time', 'change_time');
    }

    protected $fillable = array('store_key', 'reference_date', 'creation_time', 'change_time', 'new_location_key',
        'user_key', 'authorizer_key', 'transaction_type_key', 'description', 'status');


}
