<?php namespace App\Model;

/**
 * Eloquent class to describe the banking_location table
 *
 * automatically generated by ModelGenerator.php
 */
class BankingLocation extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'banking_location';

    public $primaryKey = 'location_key';

    public $timestamps = false;

    protected $fillable = array('store_key', 'loc_type', 'loc_name', 'loc_name_alt', 'loc_address', 'loc_neig',
        'loc_city', 'loc_state', 'loc_zip', 'loc_bank', 'loc_branch', 'loc_account', 'loc_cmc', 'loc_ident');


}
