<?php namespace App\Model;

/**
 * Eloquent class to describe the banking_unit table
 *
 * automatically generated by ModelGenerator.php
 */
class BankingUnit extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'banking_unit';

    public $primaryKey = 'banking_unit_key';

    public $timestamps = false;

    public function getDates()
    {
        return array('creation_time', 'date_due');
    }

    protected $fillable = array('type', 'status', 'location_key', 'store_key', 'pos_number', 'ticket_number',
        'pickup_ticket_number', 'customer_key', 'issuer_id', 'creation_time', 'media_id', 'left_in_drawer', 'is_check',
        'amount_pos', 'amount_pos_entered', 'amount_declared', 'amount_verified', 'unit_value', 'bank', 'branch', 'account',
        'check_number', 'cmc7', 'card_number', 'date_due', 'cashier_key', 'authorizer_key', 'verifier_key', 'extended_media_id',
        'pickup_transaction_number');


}
