<?php namespace App\Model;

/**
 * Eloquent class to describe the banking_transaction_type table
 *
 * automatically generated by ModelGenerator.php
 */
class BankingTransactionType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'banking_transaction_type';

    public $primaryKey = 'transaction_type_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('description', 'type', 'observation');


}
