<?php namespace App\Model;

/**
 * Eloquent class to describe the banking_media table
 *
 * automatically generated by ModelGenerator.php
 */
class BankingMedia extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'banking_media';

    public $primaryKey = 'sequence';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('media_id', 'amount', 'document_control', 'transaction_number');


}
