<?php namespace App\Model;

/**
 * Eloquent class to describe the banking_gas_cashier table
 *
 * automatically generated by ModelGenerator.php
 */
class BankingGasCashier extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'banking_gas_cashier';

    public $primaryKey = 'start_time';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('cashier_key');


}
