<?php namespace App\Model;

/**
 * Eloquent class to describe the bin_type table
 *
 * automatically generated by ModelGenerator.php
 */
class BinType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'bin_type';

    public $primaryKey = 'bin_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('bin_name', 'acquirr_key');


}
