<?php namespace App\Model;

/**
 * Eloquent class to describe the cashier_z table
 *
 * automatically generated by ModelGenerator.php
 */
class CashierZ extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cashier_z';

    public $primaryKey = 'start_time';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('cashier_key', 'authorizer_key', 'status', 'transaction_number');


}
