<?php namespace App\Model;

/**
 * Eloquent class to describe the cashier_z_media table
 *
 * automatically generated by ModelGenerator.php
 */
class CashierZMedia extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cashier_z_media';

    public $primaryKey = 'sequence';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('media_id', 'document_control', 'amount_entered', 'amount_voided', 'amount_loan',
        'amount_pickup', 'transaction_number');


}
