<?php namespace App\Model;

/**
 * Eloquent class to describe the cashier_document_data table
 *
 * automatically generated by ModelGenerator.php
 */
class CashierDocumentData extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cashier_document_data';

    public $primaryKey = 'data_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('data_value', 'data_extra');


}
