<?php namespace App\Model;

/**
 * Eloquent class to describe the cashier_counter table
 *
 * automatically generated by ModelGenerator.php
 */
class CashierCounter extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cashier_counter';

    public $primaryKey = 'counter_number';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('counter_times', 'counter_qty', 'counter_amount');


}
