<?php namespace App\Model;

/**
 * Eloquent class to describe the cashier_document table
 *
 * automatically generated by ModelGenerator.php
 */
class CashierDocument extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cashier_document';

    public $primaryKey = 'cashier_document_key';

    public $timestamps = false;

    protected $fillable = array('picked', 'swap_type', 'pickup_ticket_number', 'ticket_number', 'cpu_clock',
        'agent_key', 'agent_id', 'media_key', 'is_check', 'negative', 'undone', 'voided', 'amount', 'amount_entered',
        'unit_value', 'document_type', 'approval', 'day', 'document_tag', 'description', 'extra_media_key', 'document_status',
        'transaction_type', 'trn_number', 'store_key', 'pos_number');


}
