<?php namespace App\Model;

/**
 * Eloquent class to describe the cashier_media table
 *
 * automatically generated by ModelGenerator.php
 */
class CashierMedia extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cashier_media';

    public $primaryKey = 'media_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('qty_entered', 'qty_voided', 'qty_loan', 'qty_pickup', 'amount_entered',
        'amount_voided', 'amount_loan', 'amount_pickup');


}
