<?php namespace App\Model;

/**
 * Eloquent class to describe the cell_operator table
 *
 * automatically generated by ModelGenerator.php
 */
class CellOperator extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cell_operator';

    public $primaryKey = 'operator_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('operator_name');


}
