<?php namespace App\Model;

/**
 * Eloquent class to describe the cest table
 *
 * automatically generated by ModelGenerator.php
 */
class Cest extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cest';

    public $primaryKey = 'cest_code';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('cest_description', 'segment', 'item');


}
