<?php namespace App\Model;

/**
 * Eloquent class to describe the cfop table
 *
 * automatically generated by ModelGenerator.php
 */
class Cfop extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cfop';

    public $primaryKey = 'cfop_from';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('cfop_to', 'cfop_desc');


}
