<?php namespace App\Model;

/**
 * Eloquent class to describe the checking_system table
 *
 * automatically generated by ModelGenerator.php
 */
class CheckingSystem extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'checking_system';

    public $primaryKey = 'checking_system_key';

    public $timestamps = false;

    public function getDates()
    {
        return array('checking_system_time');
    }

    protected $fillable = array('store_key', 'pos_number', 'checking_system_type', 'checking_system_time',
        'checking_system_data');


}
