<?php namespace App\Model;

/**
 * Eloquent class to describe the city table
 *
 * automatically generated by ModelGenerator.php
 */
class City extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'city';

    public $primaryKey = 'city_code';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('state_code', 'city_name', 'city_name_sound');


}
