<?php namespace App\Model;

/**
 * Eloquent class to describe the comparison_type table
 *
 * automatically generated by ModelGenerator.php
 */
class ComparisonType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'comparison_type';

    public $primaryKey = 'type';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('label');


}
