<?php namespace App\Model;

/**
 * Eloquent class to describe the competitor table
 *
 * automatically generated by ModelGenerator.php
 */
class Competitor extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'competitor';

    public $primaryKey = 'compet_key';

    public $timestamps = false;

    protected $fillable = array('store_key', 'compet_name', 'compet_flag', 'compet_address', 'compet_comple',
        'compet_neig', 'compet_city', 'compet_state', 'compet_zip', 'compet_email', 'compet_site', 'compet_phone',
        'compet_contact', 'compet_country_code', 'compet_state_code', 'compet_city_code', 'compet_status');


}
