<?php namespace App\Model;

/**
 * Eloquent class to describe the competitor_research table
 *
 * automatically generated by ModelGenerator.php
 */
class CompetitorResearch extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'competitor_research';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('research_date');
    }

    protected $fillable = array('research_key', 'store_key', 'compet_key', 'plu_key', 'price', 'research_date');


}
