<?php namespace App\Model;

/**
 * Eloquent class to describe the comparison table
 *
 * automatically generated by ModelGenerator.php
 */
class Comparison extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'comparison';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('type', 'label', 'f1_data', 'f2_data', 'f3_data', 'f4_data', 'f5_data', 'to_data');


}
