<?php namespace App\Model;

/**
 * Eloquent class to describe the cost_center table
 *
 * automatically generated by ModelGenerator.php
 */
class CostCenter extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cost_center';

    public $primaryKey = 'cstc_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('cstc_name');


}
