<?php namespace App\Model;

/**
 * Eloquent class to describe the cost table
 *
 * automatically generated by ModelGenerator.php
 */
class Cost extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cost';

    public $primaryKey = 'store_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('cost');


}
