<?php namespace App\Model;

/**
 * Eloquent class to describe the counter_adder table
 *
 * automatically generated by ModelGenerator.php
 */
class CounterAdder extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'counter_adder';

    public $primaryKey = 'counter_type';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('counter_fiscal_date');
    }

    protected $fillable = array('counter_fiscal_date', 'amount');


}
