<?php namespace App\Model;

/**
 * Eloquent class to describe the cst_block_department table
 *
 * automatically generated by ModelGenerator.php
 */
class CstBlockDepartment extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cst_block_department';

    public $primaryKey = 'department_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_change_time');
    }

    protected $fillable = array('last_change_time');


}
