<?php namespace App\Model;

/**
 * Eloquent class to describe the cst_delayed_payment table
 *
 * automatically generated by ModelGenerator.php
 */
class CstDelayedPayment extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cst_delayed_payment';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('customer_type', 'store_key', 'media_id', 'days', 'interest', 'plan_id', 'name',
        'interest_type', 'allow_negotiation');


}
