<?php namespace App\Model;

/**
 * Eloquent class to describe the cst_fiscal_type table
 *
 * automatically generated by ModelGenerator.php
 */
class CstFiscalType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cst_fiscal_type';

    public $primaryKey = 'cst_fiscal_type_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('cst_fiscal_type_last_change_time');
    }

    protected $fillable = array('cst_fiscal_type_name', 'cst_fiscal_type_invoice', 'cst_fiscal_type_last_change_time',
        'cst_fiscal_type_price', 'cst_fiscal_tax_exception');


}
