<?php namespace App\Model;

/**
 * Eloquent class to describe the cst_type table
 *
 * automatically generated by ModelGenerator.php
 */
class CstType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cst_type';

    public $primaryKey = 'cst_type_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_change_time');
    }

    protected $fillable = array('cst_name', 'cst_discount', 'cst_second_ticket', 'cst_type_price', 'cst_extra_discount',
        'cst_extra_type_price', 'last_change_time');


}
