<?php namespace App\Model;

/**
 * Eloquent class to describe the cupom_dotz table
 *
 * automatically generated by ModelGenerator.php
 */
class CupomDotz extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cupom_dotz';

    public $primaryKey = 'crypt_password';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('valid_date', 'cupom_dotz_date_inc', 'cupom_dotz_date_alt', 'start_time');
    }

    protected $fillable = array('ticket_amount', 'valid_date', 'allow_change', 'minimum_sale_amount',
        'cupom_dotz_date_inc', 'cupom_dotz_date_alt', 'store_key', 'pos_number', 'ticket_number', 'start_time', 'amount_due',
        'plu_key', 'quantity');


}
