<?php namespace App\Model;

/**
 * Eloquent class to describe the customer_summary table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomerSummary extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'customer_summary';

    public $primaryKey = 'summary_sequence';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('summary_date_check', 'summary_date_payment', 'summary_date_alt');
    }

    protected $fillable = array('customer_id', 'cashier_key', 'authorizer_key', 'summary_bank', 'summary_branch',
        'summary_account', 'summary_check', 'summary_date_check', 'summary_date_payment', 'summary_amount', 'summary_status',
        'summary_type', 'summary_alinea', 'summary_user', 'summary_date_alt', 'void_ticket_number');


}
