<?php namespace App\Model;

/**
 * Eloquent class to describe the customer_plates table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomerPlates extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'customer_plates';

    public $primaryKey = 'plate_number';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('brand', 'model', 'km');


}
