<?php namespace App\Model;

/**
 * Eloquent class to describe the custodiam_process table
 *
 * automatically generated by ModelGenerator.php
 */
class CustodiamProcess extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'custodiam_process';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('szLastTime', 'szLastMoveTime', 'szLastContact', 'szLastConciliare', 'szNextConciliare');
    }

    protected $fillable = array('iStatus', 'iProcessMove', 'iProcessXML', 'szLastTime', 'szLastMoveTime',
        'szLastContact', 'szLastConciliare', 'szNextConciliare', 'iConcStatus');


}
