<?php namespace App\Model;

/**
 * Eloquent class to describe the customer_oblata table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomerOblata extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'customer_oblata';

    public $primaryKey = 'customer_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('promotion_points', 'promotion_points_left');


}
