<?php namespace App\Model;

/**
 * Eloquent class to describe the custodiam_ticket table
 *
 * automatically generated by ModelGenerator.php
 */
class CustodiamTicket extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'custodiam_ticket';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('dhEmi', 'szMoveTime', 'szSendTime', 'dhEnvioLote', 'dhProcessamento');
    }

    protected $fillable = array('nCnpj', 'cUF', 'nMod', 'nSerieSAT', 'cCFe', 'cNF', 'cDv', 'dhEmi', 'nNumeroCaixa',
        'cID', 'fVCFe', 'sStatus', 'iRslMessage', 'iRslCode', 'iConcEmp', 'iConcSfz', 'iConcFio', 'szMoveTime', 'szSendTime',
        'NRec', 'dhEnvioLote', 'dhProcessamento', 'Situacao');


}
