<?php namespace App\Model;

/**
 * Eloquent class to describe the customer_store table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomerStore extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'customer_store';

    public $primaryKey = 'store_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_sale_time', 'last_change_time');
    }

    protected $fillable = array('last_sale_time', 'qty_sale', 'last_change_time');


}
