<?php namespace App\Model;

/**
 * Eloquent class to describe the customer_dependents table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomerDependents extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'customer_dependents';

    public $primaryKey = 'dependent_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('dependent_name');


}
