<?php namespace App\Model;

/**
 * Eloquent class to describe the custodiam_store table
 *
 * automatically generated by ModelGenerator.php
 */
class CustodiamStore extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'custodiam_store';

    public $primaryKey = 'store_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('store_id1', 'store_name');


}
