<?php namespace App\Model;

/**
 * Eloquent class to describe the customer_answer table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomerAnswer extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'customer_answer';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('start_time');
    }

    protected $fillable = array('store_key', 'pos_number', 'ticket_number', 'start_time', 'poll_key', 'poll_type',
        'question_number', 'question_type', 'answer_number', 'answer_text', 'customer_key', 'cst_type_key');


}
