<?php namespace App\Model;

/**
 * Eloquent class to describe the customer_category table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomerCategory extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'customer_category';

    public $primaryKey = 'cst_type_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
