<?php namespace App\Model;

/**
 * Eloquent class to describe the customer_external table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomerExternal extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'customer_external';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('customer_start_time', 'customer_received_time', 'customer_effective_date');
    }

    protected $fillable = array('customer_key', 'customer_store_key', 'customer_pos_number', 'customer_ticket_number',
        'customer_start_time', 'customer_received_time', 'customer_prize_coupon', 'customer_points', 'customer_token',
        'customer_effective_date', 'customer_status');


}
