<?php namespace App\Model;

/**
 * Eloquent class to describe the custodiam_data table
 *
 * automatically generated by ModelGenerator.php
 */
class CustodiamData extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'custodiam_data';

    public $primaryKey = 'custodiam_action_type';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('custodiam_partner', 'custodiam_url', 'custodiam_name_space',
        'custodiam_ws_submit_format', 'custodiam_ws_query_format');


}
