<?php namespace App\Model;

/**
 * Eloquent class to describe the customer_oblata_trn_pts table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomerOblataTrnPts extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'customer_oblata_trn_pts';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('date_transaction');
    }

    protected $fillable = array('promotion_key', 'customer_key', 'promotion_points', 'date_transaction', 'agent_id',
        'type_transaction', 'reason_type_key', 'pos_number', 'store_key', 'ticket_number', 'trn_number');


}
