<?php namespace App\Model;

/**
 * Eloquent class to describe the customer_status table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomerStatus extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'customer_status';

    public $primaryKey = 'customer_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('customer_date_discount', 'customer_qtt_date', 'customer_idt_date');
    }

    protected $fillable = array('customer_status', 'customer_limit', 'customer_amount_left', 'customer_points',
        'customer_comment', 'customer_message', 'customer_flag_message', 'customer_flag_discount', 'customer_date_discount',
        'customer_qtt_limit', 'customer_qtt_left', 'customer_qtt_date', 'customer_flag_invoice', 'customer_idt_limit',
        'customer_idt_left', 'customer_idt_date');


}
