<?php namespace App\Model;

/**
 * Eloquent class to describe the custodiam_pos table
 *
 * automatically generated by ModelGenerator.php
 */
class CustodiamPos extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'custodiam_pos';

    public $primaryKey = 'pos_number';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('pos_name');


}
