<?php namespace App\Model;

/**
 * Eloquent class to describe the dashboard_conc_header table
 *
 * automatically generated by ModelGenerator.php
 */
class DashboardConcHeader extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'dashboard_conc_header';

    public $primaryKey = 'nrec';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('fiscal_date', 'dhenviolote', 'dhprocessamento', 'last_sent_time');
    }

    protected $fillable = array('store_key', 'fiscal_date', 'dhenviolote', 'dhprocessamento', 'tipoLote', 'origem',
        'qtdecupoms', 'situacaolote', 'last_sent_time');


}
