<?php namespace App\Model;

/**
 * Eloquent class to describe the dashboard_parameter table
 *
 * automatically generated by ModelGenerator.php
 */
class DashboardParameter extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'dashboard_parameter';

    public $primaryKey = 'prm_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('prm_value', 'agent_id');


}
