<?php namespace App\Model;

/**
 * Eloquent class to describe the dashboard_question table
 *
 * automatically generated by ModelGenerator.php
 */
class DashboardQuestion extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'dashboard_question';

    public $primaryKey = 'question_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('question_value', 'question_action');


}
