<?php namespace App\Model;

/**
 * Eloquent class to describe the dashboard_notification table
 *
 * automatically generated by ModelGenerator.php
 */
class DashboardNotification extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'dashboard_notification';

    public $primaryKey = 'ticket_number';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('notification_type', 'transaction_type', 'status', 'units', 'process_id', 'trn_number',
        'cashier_key', 'authorizer_key', 'notification_data');


}
