<?php namespace App\Model;

/**
 * Eloquent class to describe the data_entry table
 *
 * automatically generated by ModelGenerator.php
 */
class DataEntry extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'data_entry';

    public $primaryKey = 'data_entry_key';

    public $timestamps = false;

    protected $fillable = array('initial_prompt', 'name');


}
