<?php namespace App\Model;

/**
 * Eloquent class to describe the department table
 *
 * automatically generated by ModelGenerator.php
 */
class Department extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'department';

    public $primaryKey = 'department_key';

    public $timestamps = false;

    protected $fillable = array('parent_department_key', 'id', 'allow_plu', 'name');


}
