<?php namespace App\Model;

/**
 * Eloquent class to describe the discount_wrappedup table
 *
 * automatically generated by ModelGenerator.php
 */
class DiscountWrappedup extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'discount_wrappedup';

    public $primaryKey = 'wrappedup_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
