<?php namespace App\Model;

/**
 * Eloquent class to describe the discount_class_restriction table
 *
 * automatically generated by ModelGenerator.php
 */
class DiscountClassRestriction extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'discount_class_restriction';

    public $primaryKey = 'class';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
