<?php namespace App\Model;

/**
 * Eloquent class to describe the discount_type table
 *
 * automatically generated by ModelGenerator.php
 */
class DiscountType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'discount_type';

    public $primaryKey = 'dst_start_time';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('dst_end_time');
    }

    protected $fillable = array('dst_name', 'dst_application', 'dst_mec', 'dst_min_quantity', 'dst_max_percent',
        'dst_max_value', 'dst_end_time', 'dst_accum_item', 'dst_accum_subtotal', 'dst_restriction', 'dst_max_accum_value',
        'dst_ind_exceed', 'dst_show_accum', 'dst_error_correction', 'dst_ind_kit', 'dst_ind_bonus', 'authorizer_key',
        'dst_require_prev_aut', 'dst_dismissal_prev_aut', 'dst_customer_require', 'dst_quant_receipt');


}
