<?php namespace App\Model;

/**
 * Eloquent class to describe the document table
 *
 * automatically generated by ModelGenerator.php
 */
class Document extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'document';

    public $primaryKey = 'document_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('start_time');
    }

    protected $fillable = array('document_type', 'document_id', 'store_key', 'pos_number', 'ticket_number',
        'start_time', 'transaction_number', 'amount');


}
