<?php namespace App\Model;

/**
 * Eloquent class to describe the dotz_file_item table
 *
 * automatically generated by ModelGenerator.php
 */
class DotzFileItem extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'dotz_file_item';

    public $primaryKey = 'plu_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('start_time', 'end_time');
    }

    protected $fillable = array('start_time', 'end_time', 'points', 'conv_factor', 'dotz_engine', 'provider_code',
        'provider_cnpj', 'partner_code');


}
