<?php namespace App\Model;

/**
 * Eloquent class to describe the dotz_send table
 *
 * automatically generated by ModelGenerator.php
 */
class DotzSend extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'dotz_send';

    public $primaryKey = 'store_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_send_time');
    }

    protected $fillable = array('last_send_time');


}
