<?php namespace App\Model;

/**
 * Eloquent class to describe the dotz_file table
 *
 * automatically generated by ModelGenerator.php
 */
class DotzFile extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'dotz_file';

    public $primaryKey = 'plu_key_list_id';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_change_time');
    }

    protected $fillable = array('plu_list_description', 'last_change_time', 'file_type');


}
