<?php namespace App\Model;

/**
 * Eloquent class to describe the entity_type table
 *
 * automatically generated by ModelGenerator.php
 */
class EntityType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'entity_type';

    public $primaryKey = 'entity_type_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('entity_type_name');


}
