<?php namespace App\Model;

/**
 * Eloquent class to describe the entity table
 *
 * automatically generated by ModelGenerator.php
 */
class Entity extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'entity';

    public $primaryKey = 'entity_key';

    public $timestamps = false;

    public function getDates()
    {
        return array('entity_last_notify', 'entity_last_check', 'entity_last_execution');
    }

    protected $fillable = array('entity_type_key', 'entity_id', 'entity_name', 'entity_external_name',
        'entity_check_interval', 'entity_notify_interval', 'entity_last_notify', 'entity_last_check', 'entity_send',
        'entity_popup', 'entity_sms', 'entity_cron_option', 'entity_cron_spec', 'entity_last_execution');


}
