<?php namespace App\Model;

/**
 * Eloquent class to describe the extra table
 *
 * automatically generated by ModelGenerator.php
 */
class Extra extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'extra';

    public $primaryKey = 'extra_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('name', 'type');


}
