<?php namespace App\Model;

/**
 * Eloquent class to describe the farm_server_store table
 *
 * automatically generated by ModelGenerator.php
 */
class FarmServerStore extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'farm_server_store';

    public $primaryKey = 'store_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
