<?php namespace App\Model;

/**
 * Eloquent class to describe the farm_globals table
 *
 * automatically generated by ModelGenerator.php
 */
class FarmGlobals extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'farm_globals';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('farm_delay');


}
