<?php namespace App\Model;

/**
 * Eloquent class to describe the fiscal_accum_item table
 *
 * automatically generated by ModelGenerator.php
 */
class FiscalAccumItem extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'fiscal_accum_item';

    public $primaryKey = 'plu_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('quantity', 'quantity_canc', 'amount', 'amount_canc', 'pos_id', 'tax_percent',
        'pis_cofins');


}
