<?php namespace App\Model;

/**
 * Eloquent class to describe the fiscal_situation table
 *
 * automatically generated by ModelGenerator.php
 */
class FiscalSituation extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'fiscal_situation';

    public $primaryKey = 'merchandise_origin';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('extra_percent', 'red_calc_base');


}
