<?php namespace App\Model;

/**
 * Eloquent class to describe the fiscal_map table
 *
 * automatically generated by ModelGenerator.php
 */
class FiscalMap extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'fiscal_map';

    public $primaryKey = 'ticket_number';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('date_alter');
    }

    protected $fillable = array('Z_number', 'initial_GT', 'final_GT', 'void', 'discount', 'increase', 'map_number',
        'ecf_number', 'initial_ticket', 'restart_count', 'ecf_serial', 'date_alter', 'user_key', 'status_inc');


}
