<?php namespace App\Model;

/**
 * Eloquent class to describe the fiscal_tax_status table
 *
 * automatically generated by ModelGenerator.php
 */
class FiscalTaxStatus extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'fiscal_tax_status';

    public $primaryKey = 'pos_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('amount', 'tax_amount', 'tax_percent', 'ecf_number');


}
