<?php namespace App\Model;

/**
 * Eloquent class to describe the fiscal_state table
 *
 * automatically generated by ModelGenerator.php
 */
class FiscalState extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'fiscal_state';

    public $primaryKey = 'fiscal_state_type';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('fiscal_state_url', 'fiscal_state_name_space', 'fiscal_state_ws_submit_format',
        'fiscal_state_ws_query_format', 'fiscal_state_ws_submit_header', 'fiscal_state_ws_query_header');


}
