<?php namespace App\Model;

/**
 * Eloquent class to describe the gas_station_intervention table
 *
 * automatically generated by ModelGenerator.php
 */
class GasStationIntervention extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'gas_station_intervention';

    public $primaryKey = 'intervention_number';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('fiscal_hour');
    }

    protected $fillable = array('intervention_reason', 'intervention_name', 'intervention_sku_co', 'intervention_sku',
        'read_value_initial', 'read_value_final', 'calibration_value', 'fiscal_hour', 'initial_number_seal',
        'final_number_seal');


}
