<?php namespace App\Model;

/**
 * Eloquent class to describe the gift_list_message table
 *
 * automatically generated by ModelGenerator.php
 */
class GiftListMessage extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'gift_list_message';

    public $primaryKey = 'gift_list_message_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('gift_list_message_text');


}
