<?php namespace App\Model;

/**
 * Eloquent class to describe the gift_list_o table
 *
 * automatically generated by ModelGenerator.php
 */
class GiftListO extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'gift_list_o';

    public $primaryKey = 'gift_list_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('gift_list_date_wedding', 'gift_list_date_inc', 'gift_list_date_alt', 'gift_list_date_ent1', 'gift_list_date_ent2', 'gift_list_date_end');
    }

    protected $fillable = array('list_type_key', 'gift_list_password', 'gift_list_status', 'groom_key', 'groom_name',
        'groom_phone', 'bride_key', 'bride_name', 'bride_phone', 'gift_list_date_wedding', 'gift_list_location',
        'gift_list_date_inc', 'gift_list_date_alt', 'gift_list_date_ent1', 'gift_list_date_ent2', 'gift_list_date_end',
        'gift_list_obs');


}
