<?php namespace App\Model;

/**
 * Eloquent class to describe the gift_list_item table
 *
 * automatically generated by ModelGenerator.php
 */
class GiftListItem extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'gift_list_item';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('long_description', 'quantity', 'sale_quantity');


}
