<?php namespace App\Model;

/**
 * Eloquent class to describe the gift_list_address table
 *
 * automatically generated by ModelGenerator.php
 */
class GiftListAddress extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'gift_list_address';

    public $primaryKey = 'custaddr_type';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
