<?php namespace App\Model;

/**
 * Eloquent class to describe the gtin_prefix table
 *
 * automatically generated by ModelGenerator.php
 */
class GtinPrefix extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'gtin_prefix';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('prefix_in', 'prefix_fin', 'ind_esp', 'country_name');


}
