<?php namespace App\Model;

/**
 * Eloquent class to describe the history_version table
 *
 * automatically generated by ModelGenerator.php
 */
class HistoryVersion extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'history_version';

    public $primaryKey = 'version_key';

    public $timestamps = false;

    public function getDates()
    {
        return array('database_update_time');
    }

    protected $fillable = array('database_version', 'database_update_time', 'system_version', 'program_upd',
        'description_upd');


}
