<?php namespace App\Model;

/**
 * Eloquent class to describe the info_nutrition table
 *
 * automatically generated by ModelGenerator.php
 */
class InfoNutrition extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'info_nutrition';

    public $primaryKey = 'plu_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('quantity_portion', 'unit_portion', 'full_part', 'decimal_household_measure',
        'household_measure', 'status', 'caloric_value', 'carbohydrates', 'protein', 'total_fat', 'saturated_fat', 'trans_fat',
        'dietary_fiber', 'sodium');


}
