<?php namespace App\Model;

/**
 * Eloquent class to describe the inventory table
 *
 * automatically generated by ModelGenerator.php
 */
class Inventory extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'inventory';

    public $primaryKey = 'inventory_date';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('count_date', 'update_date');
    }

    protected $fillable = array('name', 'count_date', 'update_date', 'count_status', 'update_status', 'count');


}
