<?php namespace App\Model;

/**
 * Eloquent class to describe the inventory_item table
 *
 * automatically generated by ModelGenerator.php
 */
class InventoryItem extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'inventory_item';

    public $primaryKey = 'sequence';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('voided', 'plu_id', 'desc_plu', 'quantity', 'unit_price', 'amount', 'cost',
        'pos_number', 'authorizer_key', 'sku_id', 'scanned', 'cpu_clock', 'pos_id', 'tax_percent');


}
