<?php namespace App\Model;

/**
 * Eloquent class to describe the inventory_count_control table
 *
 * automatically generated by ModelGenerator.php
 */
class InventoryCountControl extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'inventory_count_control';

    public $primaryKey = 'count_number';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('status');


}
