<?php namespace App\Model;

/**
 * Eloquent class to describe the invoice_type table
 *
 * automatically generated by ModelGenerator.php
 */
class InvoiceType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'invoice_type';

    public $primaryKey = 'invoice_type_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('invoice_last_change_time');
    }

    protected $fillable = array('invoice_name', 'invoice_print', 'invoice_in_out', 'invoice_cfop', 'invoice_cfop_inter',
        'invoice_cfop_st', 'invoice_cfop_st_inter', 'invoice_comment', 'invoice_message', 'invoice_last_change_time',
        'invoice_extra_type', 'invoice_receipt');


}
