<?php namespace App\Model;

/**
 * Eloquent class to describe the list_type table
 *
 * automatically generated by ModelGenerator.php
 */
class ListType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'list_type';

    public $primaryKey = 'list_type_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('list_type_name', 'bonus_percent', 'delivery');


}
