<?php namespace App\Model;

/**
 * Eloquent class to describe the lmc_sequence table
 *
 * automatically generated by ModelGenerator.php
 */
class LmcSequence extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'lmc_sequence';

    public $primaryKey = 'fiscal_date';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_change_time');
    }

    protected $fillable = array('sequence', 'lmc_type', 'lmc_obs', 'last_change_time');


}
