<?php namespace App\Model;

/**
 * Eloquent class to describe the maker table
 *
 * automatically generated by ModelGenerator.php
 */
class Maker extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'maker';

    public $primaryKey = 'maker_key';

    public $timestamps = false;

    protected $fillable = array('maker_id', 'maker_id_type', 'maker_name', 'maker_razao', 'maker_address',
        'maker_comple', 'maker_neig', 'maker_city', 'maker_state', 'maker_zip', 'maker_email', 'maker_site', 'maker_phone1',
        'maker_phone2', 'maker_contact', 'maker_country_code', 'maker_state_code', 'maker_city_code');


}
