<?php namespace App\Model;

/**
 * Eloquent class to describe the maker_sku table
 *
 * automatically generated by ModelGenerator.php
 */
class MakerSku extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'maker_sku';

    public $primaryKey = 'maker_sku_type_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_change_time');
    }

    protected $fillable = array('maker_key', 'maker_sku_status', 'last_change_time');


}
