<?php namespace App\Model;

/**
 * Eloquent class to describe the media table
 *
 * automatically generated by ModelGenerator.php
 */
class Media extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'media';

    public $primaryKey = 'media_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('is_check', 'is_document', 'is_credit_card', 'is_debit_card', 'is_extended',
        'base_card_media_id');


}
