<?php namespace App\Model;

/**
 * Eloquent class to describe the mef table
 *
 * automatically generated by ModelGenerator.php
 */
class Mef extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'mef';

    public $primaryKey = 'trn_number';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('fiscal_date');
    }

    protected $fillable = array('ticket_number', 'ecf_number', 'fiscal_date', 'mef_text');


}
