<?php namespace App\Model;

/**
 * Eloquent class to describe the message table
 *
 * automatically generated by ModelGenerator.php
 */
class Message extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'message';

    public $primaryKey = 'message_lang';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('message_subject', 'message_text');


}
