<?php namespace App\Model;

/**
 * Eloquent class to describe the minutrade table
 *
 * automatically generated by ModelGenerator.php
 */
class Minutrade extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'minutrade';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('start_time', 'send_time', 'effective_date');
    }

    protected $fillable = array('store_key', 'pos_number', 'ticket_number', 'start_time', 'send_time', 'customer_token',
        'mobile', 'effective_date', 'status', 'http_code', 'request_data');


}
