<?php namespace App\Model;

/**
 * Eloquent class to describe the ncm table
 *
 * automatically generated by ModelGenerator.php
 */
class Ncm extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'ncm';

    public $primaryKey = 'ncm_ex';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('ncm_vigbegin', 'ncm_vigend');
    }

    protected $fillable = array('description', 'unit', 'ncm_table', 'ncm_aliqnac', 'ncm_aliqimp', 'ncm_aliqstate',
        'ncm_aliqmunicipal', 'ncm_vigbegin', 'ncm_vigend', 'ncm_code', 'ncm_version', 'ncm_source');


}
