<?php namespace App\Model;

/**
 * Eloquent class to describe the ncm_cest table
 *
 * automatically generated by ModelGenerator.php
 */
class NcmCest extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'ncm_cest';

    public $primaryKey = 'cest_code';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
