<?php namespace App\Model;

/**
 * Eloquent class to describe the nfce_event table
 *
 * automatically generated by ModelGenerator.php
 */
class NfceEvent extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'nfce_event';

    public $primaryKey = 'event_time';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('event_status', 'event_desc');


}
