<?php namespace App\Model;

/**
 * Eloquent class to describe the nfce_count_files table
 *
 * automatically generated by ModelGenerator.php
 */
class NfceCountFiles extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'nfce_count_files';

    public $primaryKey = 'pos_number';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('start_time');
    }

    protected $fillable = array('start_time', 'quantity');


}
