<?php namespace App\Model;

/**
 * Eloquent class to describe the nozzle table
 *
 * automatically generated by ModelGenerator.php
 */
class Nozzle extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'nozzle';

    public $primaryKey = 'nozzle_number';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('pump_number', 'increase_gt_qty', 'increase_gt_amo');


}
