<?php namespace App\Model;

/**
 * Eloquent class to describe the np_sku_id table
 *
 * automatically generated by ModelGenerator.php
 */
class NpSkuId extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'np_sku_id';

    public $primaryKey = 'np_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
