<?php namespace App\Model;

/**
 * Eloquent class to describe the paf_media table
 *
 * automatically generated by ModelGenerator.php
 */
class PafMedia extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'paf_media';

    public $primaryKey = 'sequence';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('ecf_number', 'trn_number', 'media_id', 'media_name', 'amount');


}
