<?php namespace App\Model;

/**
 * Eloquent class to describe the paf_ticket table
 *
 * automatically generated by ModelGenerator.php
 */
class PafTicket extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'paf_ticket';

    public $primaryKey = 'start_time';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('fiscal_date');
    }

    protected $fillable = array('paf_ticket_type', 'ecf_number', 'trn_number', 'fiscal_date', 'GNF', 'GRG', 'CDC',
        'CCF', 'trn_status');


}
