<?php namespace App\Model;

/**
 * Eloquent class to describe the password_history table
 *
 * automatically generated by ModelGenerator.php
 */
class PasswordHistory extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'password_history';

    public $primaryKey = 'last_change_time';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('cript_password');


}
