<?php namespace App\Model;

/**
 * Eloquent class to describe the password_policy table
 *
 * automatically generated by ModelGenerator.php
 */
class PasswordPolicy extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'password_policy';

    public $primaryKey = 'security_level';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('security_name', 'max_size', 'min_size', 'period', 'pass_not_name', 'pass_not_id',
        'pass_not_seq', 'pass_not_special', 'pass_special', 'pass_numeric', 'pass_letters', 'pass_upper_case', 'open_pass',
        'period_warning', 'option_01', 'option_02', 'option_03', 'option_04', 'option_05');


}
