<?php namespace App\Model;

/**
 * Eloquent class to describe the plan_store_plu table
 *
 * automatically generated by ModelGenerator.php
 */
class PlanStorePlu extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'plan_store_plu';

    public $primaryKey = 'plu_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_change_time');
    }

    protected $fillable = array('last_change_time');


}
