<?php namespace App\Model;

/**
 * Eloquent class to describe the plan table
 *
 * automatically generated by ModelGenerator.php
 */
class Plan extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'plan';

    public $primaryKey = 'plan_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('plan_start_time', 'plan_end_time', 'last_change_time');
    }

    protected $fillable = array('cst_type_key', 'media_id', 'media_sub_id', 'plan_min_payment', 'plan_max_payment',
        'plan_rate', 'plan_name', 'plan_min_amount', 'plan_status', 'plan_start_time', 'plan_end_time', 'last_change_time',
        'option_01', 'option_02', 'option_03', 'option_04', 'option_05', 'option_06', 'option_07', 'option_08', 'option_09',
        'option_10');


}
