<?php namespace App\Model;

/**
 * Eloquent class to describe the plan_split_code table
 *
 * automatically generated by ModelGenerator.php
 */
class PlanSplitCode extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'plan_split_code';

    public $primaryKey = 'plan_split_code_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('plan_split_code_desc');


}
