<?php namespace App\Model;

/**
 * Eloquent class to describe the plan_plu_split_amount table
 *
 * automatically generated by ModelGenerator.php
 */
class PlanPluSplitAmount extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'plan_plu_split_amount';

    public $primaryKey = 'ppsa_key';

    public $timestamps = false;

    public function getDates()
    {
        return array('ppsa_start_time', 'ppsa_end_time', 'last_change_time');
    }

    protected $fillable = array('store_key', 'plu_key', 'cst_type_key', 'media_id', 'media_sub_id', 'ppsa_splits',
        'ppsa_split_amount', 'ppsa_status', 'ppsa_start_time', 'ppsa_end_time', 'ppsa_interest_percent',
        'ppsa_delayed_payment_percent', 'last_change_time');


}
