<?php namespace App\Model;

/**
 * Eloquent class to describe the plu_batch_stock table
 *
 * automatically generated by ModelGenerator.php
 */
class PluBatchStock extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'plu_batch_stock';

    public $primaryKey = 'batch';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('batch_manufacture', 'batch_expiration', 'last_change_time');
    }

    protected $fillable = array('batch_manufacture', 'batch_expiration', 'quantity_in_stock', 'last_change_time');


}
