<?php namespace App\Model;

/**
 * Eloquent class to describe the plu_extra table
 *
 * automatically generated by ModelGenerator.php
 */
class PluExtra extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'plu_extra';

    public $primaryKey = 'extra_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('extra_value');


}
