<?php namespace App\Model;

/**
 * Eloquent class to describe the plu_pack table
 *
 * automatically generated by ModelGenerator.php
 */
class PluPack extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'plu_pack';

    public $primaryKey = 'plu_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
