<?php namespace App\Model;

/**
 * Eloquent class to describe the plu_store_label table
 *
 * automatically generated by ModelGenerator.php
 */
class PluStoreLabel extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'plu_store_label';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('store_key', 'plu_key', 'label_type', 'label_address', 'label_count');


}
