<?php namespace App\Model;

/**
 * Eloquent class to describe the plu_store_service table
 *
 * automatically generated by ModelGenerator.php
 */
class PluStoreService extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'plu_store_service';

    public $primaryKey = 'service_start_time';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('service_end_time');
    }

    protected $fillable = array('service_end_time', 'service_price', 'service_cost', 'service_maker_period',
        'service_code');


}
