<?php namespace App\Model;

/**
 * Eloquent class to describe the plu_type table
 *
 * automatically generated by ModelGenerator.php
 */
class PluType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'plu_type';

    public $primaryKey = 'plu_type';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('name');


}
