<?php namespace App\Model;

/**
 * Eloquent class to describe the poll_store table
 *
 * automatically generated by ModelGenerator.php
 */
class PollStore extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'poll_store';

    public $primaryKey = 'poll_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
