<?php namespace App\Model;

/**
 * Eloquent class to describe the poll_question_answer table
 *
 * automatically generated by ModelGenerator.php
 */
class PollQuestionAnswer extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'poll_question_answer';

    public $primaryKey = 'answer_number';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('answer_text');


}
