<?php namespace App\Model;

/**
 * Eloquent class to describe the poll_department table
 *
 * automatically generated by ModelGenerator.php
 */
class PollDepartment extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'poll_department';

    public $primaryKey = 'poll_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
