<?php namespace App\Model;

/**
 * Eloquent class to describe the poll_cst_type table
 *
 * automatically generated by ModelGenerator.php
 */
class PollCstType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'poll_cst_type';

    public $primaryKey = 'poll_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
