<?php namespace App\Model;

/**
 * Eloquent class to describe the poll_question table
 *
 * automatically generated by ModelGenerator.php
 */
class PollQuestion extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'poll_question';

    public $primaryKey = 'question_number';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('question_type', 'question_label', 'question_prompt');


}
