<?php namespace App\Model;

/**
 * Eloquent class to describe the poll table
 *
 * automatically generated by ModelGenerator.php
 */
class Poll extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'poll';

    public $primaryKey = 'poll_key';

    public $timestamps = false;

    public function getDates()
    {
        return array('start_time', 'finish_time');
    }

    protected $fillable = array('poll_type', 'poll_name', 'poll_display_name', 'start_time', 'finish_time');


}
