<?php namespace App\Model;

/**
 * Eloquent class to describe the pos table
 *
 * automatically generated by ModelGenerator.php
 */
class Pos extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'pos';

    public $primaryKey = 'pos_number';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('pos_date_inc', 'pos_date_alt', 'pos_contact', 'pos_last_plu_export_time', 'pos_last_plu_update_time', 'pos_last_customer_export_time', 'pos_last_customer_update_time', 'info_time', 'last_user_update_time', 'last_user_autosend_check', 'last_user_autosend_time', 'pos_nfce_time', 'cert_expr_date', 'pos_sat_time');
    }

    protected $fillable = array('pos_decimals', 'pos_name', 'pos_serial', 'pos_version', 'pos_impress', 'pos_checkout',
        'pos_date_inc', 'pos_date_alt', 'pos_status', 'pos_contact', 'pos_model', 'pos_IP', 'pos_system', 'pos_invoice_printer',
        'pos_last_plu_update', 'pos_last_customer_update', 'pos_data', 'pos_transmit_type', 'pos_last_plu_export_time',
        'pos_last_plu_update_time', 'pos_last_customer_export_time', 'pos_last_customer_update_time', 'pos_internal_ip',
        'pos_internal_port', 'pos_automatic_option', 'pos_rec_status', 'pos_type_key', 'pos_emergency_status', 'pos_plu_type',
        'info_time', 'os_name', 'os_version', 'os_code', 'cpu_count', 'memory_total', 'swap_total', 'swap_free',
        'last_user_update_time', 'last_user_update', 'user_autosend', 'last_user_autosend_check', 'user_autosend_changed',
        'last_user_autosend_time', 'pos_nfce_time', 'pos_active', 'cert_expr_date', 'pos_sat_time');


}
