<?php namespace App\Model;

/**
 * Eloquent class to describe the pos_cpu table
 *
 * automatically generated by ModelGenerator.php
 */
class PosCpu extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'pos_cpu';

    public $primaryKey = 'processor_number';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('vendor_id', 'cpu_family', 'model', 'model_name', 'stepping', 'cpu_mhz', 'cache_size',
        'physical_id', 'siblings', 'core_id', 'cpu_cores', 'fpu', 'fpu_exception', 'cpuid_level', 'wp', 'flags', 'bogomips',
        'clflush_size');


}
