<?php namespace App\Model;

/**
 * Eloquent class to describe the pos_operation table
 *
 * automatically generated by ModelGenerator.php
 */
class PosOperation extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'pos_operation';

    public $primaryKey = 'start_time';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('cashier_key', 'authorizer_key', 'pos_oper_type', 'pos_oper_data1', 'pos_oper_data2',
        'pos_oper_data3', 'pos_oper_data4');


}
