<?php namespace App\Model;

/**
 * Eloquent class to describe the pos_program table
 *
 * automatically generated by ModelGenerator.php
 */
class PosProgram extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'pos_program';

    public $primaryKey = 'program_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('program_version', 'program_version_line', 'program_executable');


}
