<?php namespace App\Model;

/**
 * Eloquent class to describe the pos_type table
 *
 * automatically generated by ModelGenerator.php
 */
class PosType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'pos_type';

    public $primaryKey = 'pos_type_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('name');


}
