<?php namespace App\Model;

/**
 * Eloquent class to describe the pos_update_control table
 *
 * automatically generated by ModelGenerator.php
 */
class PosUpdateControl extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'pos_update_control';

    public $primaryKey = 'start_time';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('transaction_status', 'process_id');


}
