<?php namespace App\Model;

/**
 * Eloquent class to describe the pricing_step table
 *
 * automatically generated by ModelGenerator.php
 */
class PricingStep extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'pricing_step';

    public $primaryKey = 'action_type';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('times', 'price', 'next_step');


}
