<?php namespace App\Model;

/**
 * Eloquent class to describe the pricing table
 *
 * automatically generated by ModelGenerator.php
 */
class Pricing extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'pricing';

    public $primaryKey = 'store_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('price', 'quantity', 'promotion', 'code_promotion', 'points', 'rate', 'sequence');


}
