<?php namespace App\Model;

/**
 * Eloquent class to describe the price table
 *
 * automatically generated by ModelGenerator.php
 */
class Price extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'price';

    public $primaryKey = 'price_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_change_time');
    }

    protected $fillable = array('name', 'last_change_time', 'adm_price');


}
