<?php namespace App\Model;

/**
 * Eloquent class to describe the produced_list table
 *
 * automatically generated by ModelGenerator.php
 */
class ProducedList extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'produced_list';

    public $primaryKey = 'plu_key_input';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('quantity');


}
