<?php namespace App\Model;

/**
 * Eloquent class to describe the produced_order_list table
 *
 * automatically generated by ModelGenerator.php
 */
class ProducedOrderList extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'produced_order_list';

    public $primaryKey = 'plu_key_input';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('base_quantity');


}
