<?php namespace App\Model;

/**
 * Eloquent class to describe the produced_order table
 *
 * automatically generated by ModelGenerator.php
 */
class ProducedOrder extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'produced_order';

    public $primaryKey = 'order_key';

    public $timestamps = false;

    public function getDates()
    {
        return array('insert_date', 'update_date', 'production_date');
    }

    protected $fillable = array('store_key', 'plu_key_prod', 'unit_key', 'base_quantity', 'quantity', 'insert_date',
        'update_date', 'production_date', 'order_status', 'cost', 'price_suggestion');


}
