<?php namespace App\Model;

/**
 * Eloquent class to describe the promotion_items table
 *
 * automatically generated by ModelGenerator.php
 */
class PromotionItems extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotion_items';

    public $primaryKey = 'plu_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('price', 'status', 'points');


}
