<?php namespace App\Model;

/**
 * Eloquent class to describe the promotion_prize_control table
 *
 * automatically generated by ModelGenerator.php
 */
class PromotionPrizeControl extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotion_prize_control';

    public $primaryKey = 'ppc_time';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('ppc_number', 'eft_trans_nsu');


}
