<?php namespace App\Model;

/**
 * Eloquent class to describe the promotion_dotz table
 *
 * automatically generated by ModelGenerator.php
 */
class PromotionDotz extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotion_dotz';

    public $primaryKey = 'plu_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('points');


}
