<?php namespace App\Model;

/**
 * Eloquent class to describe the promotion_item table
 *
 * automatically generated by ModelGenerator.php
 */
class PromotionItem extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotion_item';

    public $primaryKey = 'item_type';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('price', 'points', 'quantity_min', 'quantity_lim', 'quantity_max', 'amount', 'status',
        'flag_discount');


}
