<?php namespace App\Model;

/**
 * Eloquent class to describe the promotion_extra_ticket table
 *
 * automatically generated by ModelGenerator.php
 */
class PromotionExtraTicket extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotion_extra_ticket';

    public $primaryKey = 'extra_ticket_type_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('extra_ticket_type_name', 'extra_ticket_header', 'extra_ticket_detail',
        'extra_ticket_footer');


}
