<?php namespace App\Model;

/**
 * Eloquent class to describe the promotion_media table
 *
 * automatically generated by ModelGenerator.php
 */
class PromotionMedia extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotion_media';

    public $primaryKey = 'splits';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('media_type', 'status');


}
