<?php namespace App\Model;

/**
 * Eloquent class to describe the promotion_external table
 *
 * automatically generated by ModelGenerator.php
 */
class PromotionExternal extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotion_external';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('start', 'finish', 'received_time', 'effective_date');
    }

    protected $fillable = array('promotion_key', 'name', 'start', 'finish', 'store_key', 'promo_type', 'promo_mode',
        'sale_status', 'sale_state', 'amount', 'received_time', 'prize_coupon', 'token', 'promo_data', 'effective_date',
        'send_pos', 'status');


}
