<?php namespace App\Model;

/**
 * Eloquent class to describe the promotion_gift table
 *
 * automatically generated by ModelGenerator.php
 */
class PromotionGift extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotion_gift';

    public $primaryKey = 'plu_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('amount', 'points', 'status');


}
