<?php namespace App\Model;

/**
 * Eloquent class to describe the promotion_external_prm table
 *
 * automatically generated by ModelGenerator.php
 */
class PromotionExternalPrm extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotion_external_prm';

    public $primaryKey = 'data_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('data_name', 'data_value', 'data_type', 'data_hidden');


}
