<?php namespace App\Model;

/**
 * Eloquent class to describe the promotion_kit table
 *
 * automatically generated by ModelGenerator.php
 */
class PromotionKit extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotion_kit';

    public $primaryKey = 'store_group_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('discount', 'flag_discount', 'points', 'count_type');


}
