<?php namespace App\Model;

/**
 * Eloquent class to describe the promotion table
 *
 * automatically generated by ModelGenerator.php
 */
class Promotion extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotion';

    public $primaryKey = 'promotion_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('start', 'finish');
    }

    protected $fillable = array('name', 'start', 'finish', 'promotion_type', 'promotion_mode', 'quantity_min',
        'quantity_lim', 'quantity_max', 'amount', 'extra_ticket_type_key', 'media_id', 'promotion_header', 'promotion_message',
        'promotion_command', 'points', 'status', 'md_partial', 'discount', 'flag_discount', 'reason_type_key', 'option_01',
        'option_02', 'option_03', 'option_04', 'option_05', 'option_06', 'option_07', 'option_08', 'option_09', 'option_10',
        'option_11', 'option_12', 'option_13', 'option_14', 'option_15', 'option_16', 'option_17', 'option_18', 'option_19',
        'option_20', 'source');


}
