<?php namespace App\Model;

/**
 * Eloquent class to describe the promotion_department table
 *
 * automatically generated by ModelGenerator.php
 */
class PromotionDepartment extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotion_department';

    public $primaryKey = 'department_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
