<?php namespace App\Model;

/**
 * Eloquent class to describe the promotion_category table
 *
 * automatically generated by ModelGenerator.php
 */
class PromotionCategory extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotion_category';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('promotion_key', 'store_key', 'store_group_key', 'cst_type_key', 'status');


}
