<?php namespace App\Model;

/**
 * Eloquent class to describe the pump_item_grand_total table
 *
 * automatically generated by ModelGenerator.php
 */
class PumpItemGrandTotal extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'pump_item_grand_total';

    public $primaryKey = 'nozzle_number';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('amount', 'qty');


}
