<?php namespace App\Model;

/**
 * Eloquent class to describe the query_item table
 *
 * automatically generated by ModelGenerator.php
 */
class QueryItem extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'query_item';

    public $primaryKey = 'sequence';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('ticket_number', 'item_sequence', 'plu_id', 'desc_plu', 'quantity', 'unit_price',
        'amount', 'cashier_key', 'authorizer_key', 'discount', 'increase', 'sku_id', 'scanned', 'context', 'type_price',
        'verifier_number');


}
