<?php namespace App\Model;

/**
 * Eloquent class to describe the reason_store table
 *
 * automatically generated by ModelGenerator.php
 */
class ReasonStore extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'reason_store';

    public $primaryKey = 'store_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
