<?php namespace App\Model;

/**
 * Eloquent class to describe the reason_type table
 *
 * automatically generated by ModelGenerator.php
 */
class ReasonType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'reason_type';

    public $primaryKey = 'reason_type_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('description', 'reason_command', 'store_key');


}
