<?php namespace App\Model;

/**
 * Eloquent class to describe the recipe_message table
 *
 * automatically generated by ModelGenerator.php
 */
class RecipeMessage extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'recipe_message';

    public $primaryKey = 'plu_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('observation', 'information', 'extra_information');


}
