<?php namespace App\Model;

/**
 * Eloquent class to describe the request_control table
 *
 * automatically generated by ModelGenerator.php
 */
class RequestControl extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'request_control';

    public $primaryKey = 'request_trn_number';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('fiscal_date');
    }

    protected $fillable = array('fiscal_date', 'trn_number', 'request_ticket_number');


}
