<?php namespace App\Model;

/**
 * Eloquent class to describe the research table
 *
 * automatically generated by ModelGenerator.php
 */
class Research extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'research';

    public $primaryKey = 'research_type';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('research_key', 'research_name', 'research_status');


}
