<?php namespace App\Model;

/**
 * Eloquent class to describe the sale_media_data table
 *
 * automatically generated by ModelGenerator.php
 */
class SaleMediaData extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sale_media_data';

    public $primaryKey = 'data_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('data_label', 'data_value');


}
