<?php namespace App\Model;

/**
 * Eloquent class to describe the sale_cfe table
 *
 * automatically generated by ModelGenerator.php
 */
class SaleCfe extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sale_cfe';

    public $primaryKey = 'sale_type';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('protocol_date', 'emit_date');
    }

    protected $fillable = array('nfce_number', 'nfce_key', 'nfce_status', 'nfce_protocol', 'sefaz_status',
        'protocol_date', 'emit_date', 'voided', 'amount_due', 'status', 'sefaz_link', 'file_path');


}
