<?php namespace App\Model;

/**
 * Eloquent class to describe the sale_promotion_department table
 *
 * automatically generated by ModelGenerator.php
 */
class SalePromotionDepartment extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sale_promotion_department';

    public $primaryKey = 'department_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
