<?php namespace App\Model;

/**
 * Eloquent class to describe the sale_extra table
 *
 * automatically generated by ModelGenerator.php
 */
class SaleExtra extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sale_extra';

    public $primaryKey = 'invoice_number';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('fiscal_date', 'emission_date');
    }

    protected $fillable = array('fiscal_date', 'sale_type', 'maker_key', 'serial', 'cfop', 'base_icms', 'icms',
        'base_subst', 'icms_subst', 'amo_items', 'frete', 'seguro', 'outras', 'ipi', 'amo_invoice', 'store2_key',
        'invoice_type', 'from_key', 'to_key', 'sale_comment', 'request_comment', 'sale_name', 'voided', 'delivery_item_id',
        'emission_date');


}
