<?php namespace App\Model;

/**
 * Eloquent class to describe the sale_item_service table
 *
 * automatically generated by ModelGenerator.php
 */
class SaleItemService extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sale_item_service';

    public $primaryKey = 'sequence';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('sis_period', 'sis_price', 'sis_discount', 'sis_increase', 'sis_cost', 'sis_type_key',
        'customer_id', 'sis_id');


}
