<?php namespace App\Model;

/**
 * Eloquent class to describe the sale_history_weight table
 *
 * automatically generated by ModelGenerator.php
 */
class SaleHistoryWeight extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sale_history_weight';

    public $primaryKey = 'sequence';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('plu_id', 'authorizer_key', 'cad_checkout_weight', 'self_checkout_weight');


}
