<?php namespace App\Model;

/**
 * Eloquent class to describe the sale_promotion_media table
 *
 * automatically generated by ModelGenerator.php
 */
class SalePromotionMedia extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sale_promotion_media';

    public $primaryKey = 'media_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
