<?php namespace App\Model;

/**
 * Eloquent class to describe the sale_media table
 *
 * automatically generated by ModelGenerator.php
 */
class SaleMedia extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sale_media';

    public $primaryKey = 'sequence';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('media_id', 'amount', 'authorizer_key', 'extended_media_id', 'cpu_clock');


}
