<?php namespace App\Model;

/**
 * Eloquent class to describe the sale_item_extra table
 *
 * automatically generated by ModelGenerator.php
 */
class SaleItemExtra extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sale_item_extra';

    public $primaryKey = 'sequence';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('cfop', 'desc_plu', 'quantity', 'unit_price', 'amount', 'discount', 'increase',
        'pos_id', 'tax_percent', 'pis_cofins', 'tax_reduction', 'tax_calculation_base', 'tax_amount', 'tax_extra_percent',
        'tolerance_max', 'tolerance_min');


}
