<?php namespace App\Model;

/**
 * Eloquent class to describe the sale_item table
 *
 * automatically generated by ModelGenerator.php
 */
class SaleItem extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sale_item';

    public $primaryKey = 'sequence';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('voided', 'plu_id', 'desc_plu', 'quantity', 'unit_price', 'amount', 'cost', 'clerk_key',
        'authorizer_key', 'discount', 'increase', 'sku_id', 'scanned', 'query_item', 'cpu_clock', 'pos_id', 'tax_percent',
        'pis_cofins', 'type_price', 'reason_price', 'transaction');


}
