<?php namespace App\Model;

/**
 * Eloquent class to describe the sat table
 *
 * automatically generated by ModelGenerator.php
 */
class Sat extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sat';

    public $primaryKey = 'sat_number';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('sat_date_inc', 'sat_date_alt', 'last_update_time', 'last_sent_time', 'last_comm_time', 'cert_create_date', 'cert_expr_date');
    }

    protected $fillable = array('sat_name', 'sat_serial', 'sat_version', 'sat_model', 'sat_date_inc', 'sat_date_alt',
        'sat_status', 'sat_manufacturer', 'sat_lan_type', 'sat_lan_IP', 'sat_lan_mask', 'sat_lan_gw', 'sat_lan_dns',
        'sat_lan_dns_alt', 'sat_mac_addr', 'sat_lan_online', 'sat_battery', 'sat_disk_space', 'sat_disk_usage',
        'last_update_time', 'sat_firmware', 'sat_layout', 'last_sent_cfe', 'first_stored_cfe', 'last_stored_cfe',
        'last_sent_time', 'last_comm_time', 'cert_create_date', 'cert_expr_date');


}
