<?php namespace App\Model;

/**
 * Eloquent class to describe the sat_model table
 *
 * automatically generated by ModelGenerator.php
 */
class SatModel extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sat_model';

    public $primaryKey = 'sat_model';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
