<?php namespace App\Model;

/**
 * Eloquent class to describe the seal_accelerators table
 *
 * automatically generated by ModelGenerator.php
 */
class SealAccelerators extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'seal_accelerators';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('store_key', 'plu_id', 'quantity_plu', 'quantity_seal', 'max_repeat_times');


}
