<?php namespace App\Model;

/**
 * Eloquent class to describe the seal_dump table
 *
 * automatically generated by ModelGenerator.php
 */
class SealDump extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'seal_dump';

    public $primaryKey = 'cashier_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('fiscal_date');
    }

    protected $fillable = array('fiscal_date', 'ticket_number', 'authorizer_key', 'operation_type', 'seal_sequence',
        'seal_last_sequence', 'remaining_seal');


}
