<?php namespace App\Model;

/**
 * Eloquent class to describe the send_routes table
 *
 * automatically generated by ModelGenerator.php
 */
class SendRoutes extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'send_routes';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_change_time');
    }

    protected $fillable = array('type_oper', 'model_type', 'store_key', 'file_path', 'file_name', 'last_change_time');


}
