<?php namespace App\Model;

/**
 * Eloquent class to describe the serasa_type table
 *
 * automatically generated by ModelGenerator.php
 */
class SerasaType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'serasa_type';

    public $primaryKey = 'serasa_type_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('serasa_type_name', 'serasa_type_msg');


}
