<?php namespace App\Model;

/**
 * Eloquent class to describe the service_control table
 *
 * automatically generated by ModelGenerator.php
 */
class ServiceControl extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'service_control';

    public $primaryKey = 'service_number';

    public $timestamps = false;

    public function getDates()
    {
        return array('start_time', 'fiscal_date', 'ref_start_time', 'ref_fiscal_date');
    }

    protected $fillable = array('service_type_key', 'store_key', 'pos_number', 'ticket_number', 'start_time',
        'transaction', 'fiscal_date', 'ref_store_key', 'ref_pos_number', 'ref_ticket_number', 'ref_start_time',
        'ref_transaction', 'ref_fiscal_date', 'cashier_key', 'authorizer_key', 'plu_id', 'sequence', 'amount', 'status',
        'reason');


}
