<?php namespace App\Model;

/**
 * Eloquent class to describe the servertoserver_store table
 *
 * automatically generated by ModelGenerator.php
 */
class ServertoserverStore extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'servertoserver_store';

    public $primaryKey = 'store_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_change_time');
    }

    protected $fillable = array('main_server_type_flag', 'sec_server_type_flag', 'last_change_time');


}
