<?php namespace App\Model;

/**
 * Eloquent class to describe the session table
 *
 * automatically generated by ModelGenerator.php
 */
class Session extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'session';

    public $primaryKey = 'session_key';

    public $timestamps = false;

    public function getDates()
    {
        return array('start_time', 'finish_time', 'update_time');
    }

    protected $fillable = array('session_id', 'agent_key', 'status', 'start_time', 'finish_time', 'update_time',
        'store_key', 'pos_number', 'terminal_ip');


}
