<?php namespace App\Model;

/**
 * Eloquent class to describe the sku table
 *
 * automatically generated by ModelGenerator.php
 */
class Sku extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sku';

    public $primaryKey = 'sku_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('plu_key');


}
