<?php namespace App\Model;

/**
 * Eloquent class to describe the sku_store_plu table
 *
 * automatically generated by ModelGenerator.php
 */
class SkuStorePlu extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sku_store_plu';

    public $primaryKey = 'plu_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
