<?php namespace App\Model;

/**
 * Eloquent class to describe the sngpc table
 *
 * automatically generated by ModelGenerator.php
 */
class Sngpc extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sngpc';

    public $primaryKey = 'register_type';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('register_date', 'prescription_date', 'last_change_time');
    }

    protected $fillable = array('store_destiny', 'register_date', 'prescription_type', 'prescription_number',
        'prescription_date', 'last_change_time', 'request_number', 'sngpc_id', 'status');


}
