<?php namespace App\Model;

/**
 * Eloquent class to describe the sngpc_control table
 *
 * automatically generated by ModelGenerator.php
 */
class SngpcControl extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sngpc_control';

    public $primaryKey = 'store_key';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('date_initial', 'date_final', 'date_create', 'date_send', 'date_last_send');
    }

    protected $fillable = array('date_initial', 'date_final', 'date_create', 'date_send', 'date_last_send', 'qty_tries',
        'notes', 'status', 'return_code', 'return_msg', 'qty_registers', 'file_path');


}
