<?php namespace App\Model;

/**
 * Eloquent class to describe the sngpc_item table
 *
 * automatically generated by ModelGenerator.php
 */
class SngpcItem extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sngpc_item';

    public $primaryKey = 'plu_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('ms_code', 'therapeutic_class', 'medicine_batch', 'medicine_quantity',
        'medicine_use_type', 'medicine_use_prolong', 'reason_type', 'package_unit_type');


}
