<?php namespace App\Model;

/**
 * Eloquent class to describe the sngpc_invoice table
 *
 * automatically generated by ModelGenerator.php
 */
class SngpcInvoice extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'sngpc_invoice';

    public $primaryKey = 'fiscal_date';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_change_time');
    }

    protected $fillable = array('store_origin', 'store_destiny', 'last_change_time');


}
