<?php namespace App\Model;

/**
 * Eloquent class to describe the status_group table
 *
 * automatically generated by ModelGenerator.php
 */
class StatusGroup extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'status_group';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('status_type_key', 'group_key');


}
