<?php namespace App\Model;

/**
 * Eloquent class to describe the state table
 *
 * automatically generated by ModelGenerator.php
 */
class State extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'state';

    public $primaryKey = 'acronym';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('name', 'timezone', 'dls_timezone', 'state_code');


}
