<?php namespace App\Model;

/**
 * Eloquent class to describe the status_type table
 *
 * automatically generated by ModelGenerator.php
 */
class StatusType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'status_type';

    public $primaryKey = 'status_type_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('status_type_name', 'status_type_msg');


}
