<?php namespace App\Model;

/**
 * Eloquent class to describe the status_sefaz table
 *
 * automatically generated by ModelGenerator.php
 */
class StatusSefaz extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'status_sefaz';

    public $primaryKey = 'status_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('status_desc', 'status_faq');


}
