<?php namespace App\Model;

/**
 * Eloquent class to describe the store_tax_type table
 *
 * automatically generated by ModelGenerator.php
 */
class StoreTaxType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'store_tax_type';

    public $primaryKey = 'tax_type_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
