<?php namespace App\Model;

/**
 * Eloquent class to describe the store_group table
 *
 * automatically generated by ModelGenerator.php
 */
class StoreGroup extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'store_group';

    public $primaryKey = 'store_group_key';

    public $timestamps = false;

    protected $fillable = array('parent_store_group_key', 'store_group_id', 'store_group_name', 'allow_store');


}
