<?php namespace App\Model;

/**
 * Eloquent class to describe the store_group_store table
 *
 * automatically generated by ModelGenerator.php
 */
class StoreGroupStore extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'store_group_store';

    public $primaryKey = 'store_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();


}
