<?php namespace App\Model;

/**
 * Eloquent class to describe the tax_type table
 *
 * automatically generated by ModelGenerator.php
 */
class TaxType extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'tax_type';

    public $primaryKey = 'tax_type_key';

    public $timestamps = false;

    protected $fillable = array('type_key', 'percent', 'extra_percent', 'description', 'pos_id', 'interest_plu',
        'allow_map', 'extra');


}
