<?php namespace App\Model;

/**
 * Eloquent class to describe the ticket_rule table
 *
 * automatically generated by ModelGenerator.php
 */
class TicketRule extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'ticket_rule';

    public $primaryKey = 'sequence';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('data_id', 'rule_condition', 'data_value', 'title', 'nor');


}
