<?php namespace App\Model;

/**
 * Eloquent class to describe the ticket table
 *
 * automatically generated by ModelGenerator.php
 */
class Ticket extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'ticket';

    public $primaryKey = 'start_time';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('fiscal_date');
    }

    protected $fillable = array('ticket_type', 'ecf_number', 'trn_number', 'fiscal_date', 'display', 'GNF', 'GRG',
        'CDC', 'CCF');


}
