<?php namespace App\Model;

/**
 * Eloquent class to describe the ticket_remarks table
 *
 * automatically generated by ModelGenerator.php
 */
class TicketRemarks extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'ticket_remarks';

    public $primaryKey = 'remark_time';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('ecf_number', 'trn_number', 'initial_GT', 'final_GT', 'item_total_GT', 'amount_due',
        'media_total', 'change_total', 'discount_total', 'item_total', 'remark');


}
