<?php namespace App\Model;

/**
 * Eloquent class to describe the transaction_status table
 *
 * automatically generated by ModelGenerator.php
 */
class TransactionStatus extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'transaction_status';

    public $primaryKey = 'trans_key';

    public $timestamps = false;

    public function getDates()
    {
        return array('trans_time_start', 'trans_time_update', 'trans_time_finish');
    }

    protected $fillable = array('trans_status', 'trans_type', 'trans_object', 'trans_store', 'trans_pos_from',
        'trans_pos_to', 'trans_IP', 'trans_user', 'trans_time_start', 'trans_time_update', 'trans_time_finish',
        'trans_total_units', 'trans_current_units', 'trans_data', 'trans_report');


}
