<?php namespace App\Model;

/**
 * Eloquent class to describe the transaction_log table
 *
 * automatically generated by ModelGenerator.php
 */
class TransactionLog extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'transaction_log';

    public $primaryKey = 'log_key';

    public $timestamps = false;

    public function getDates()
    {
        return array('start_time');
    }

    protected $fillable = array('access_type_key', 'start_time', 'user_id', 'terminal_ip', 'entity_type_key', 'entity',
        'program_file', 'key_value', 'new_data');


}
