<?php namespace App\Model;

/**
 * Eloquent class to describe the treasury_media_history table
 *
 * automatically generated by ModelGenerator.php
 */
class TreasuryMediaHistory extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'treasury_media_history';

    public $primaryKey = 'date_alter';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('media_id', 'amount', 'amount_new', 'user_key', 'reason_type_key', 'trans_type');


}
