<?php namespace App\Model;

/**
 * Eloquent class to describe the type table
 *
 * automatically generated by ModelGenerator.php
 */
class Type extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'type';

    public $primaryKey = 'type_key';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('name');


}
