<?php namespace App\Model;

/**
 * Eloquent class to describe the wsnfp table
 *
 * automatically generated by ModelGenerator.php
 */
class Wsnfp extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'wsnfp';

    public $primaryKey = 'wsnfp_key';

    public $timestamps = false;

    public function getDates()
    {
        return array('initial_fiscal_day', 'final_fiscal_day', 'start_time', 'sent_time', 'result_time', 'check_time');
    }

    protected $fillable = array('file_name', 'cnpj', 'store_key', 'ecf_serial', 'initial_fiscal_day',
        'final_fiscal_day', 'wsnfp_status', 'start_time', 'sent_time', 'result_time', 'check_time', 'rsl_send_hora',
        'rsl_send_lote', 'rsl_send_cod_situacao', 'rsl_send_situacao', 'rsl_proc_data', 'rsl_proc_data_referencia',
        'rsl_proc_alertas', 'rsl_proc_quantidade', 'rsl_proc_razao_social', 'rsl_proc_observacoes', 'rsl_proc_responsavel',
        'rsl_proc_tipo', 'rsl_proc_arquivo', 'rsl_proc_hash', 'rsl_proc_tempo', 'rsl_proc_cupons', 'rsl_proc_tamanho',
        'rsl_proc_valor', 'rsl_proc_mensagens', 'rsl_proc_cod_situacao', 'md5');


}
