<?php namespace App\Model;

/**
 * Eloquent class to describe the wsnfp_mensagens table
 *
 * automatically generated by ModelGenerator.php
 */
class WsnfpMensagens extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'wsnfp_mensagens';

    public $primaryKey = 'store_state';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('rsl_proc_mensagens', 'rsl_action');


}
