<?php namespace App\Model;

/**
 * Eloquent class to describe the wsnfp_status table
 *
 * automatically generated by ModelGenerator.php
 */
class WsnfpStatus extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'wsnfp_status';

    public $primaryKey = 'fiscal_date';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('last_export_time', 'last_xml_process_time', 'last_check_time');
    }

    protected $fillable = array('status_mov', 'status_trn', 'observation', 'user', 'last_wsnfp_key', 'last_export_time',
        'last_xml_process_time', 'last_check_time', 'last_trans_key', 'pos_number', 'ecf_status');


}
